import { Component } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-landing-page',
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.css']
})
export class LandingPageComponent {
  constructor(private router: Router, private route: ActivatedRoute){}
  openFirstArticle = () =>{
    localStorage.setItem("articleObj", `{
    "title": "15 Benefits Of Book Reading",
    "tags": ["Books", "Benefits", "Reading"],
    "link": "https://miro.medium.com/v2/resize:fit:1400/0*k7kBs3oB__hG6-RH",
    "content": [
      {"heading": "Why Book Reading Important?", "subHeading": "", "description": "Sticks are full of all kinds of information, story, thoughts, and feelings of anything in this world. Can words, paragraphs, and imaginary worlds be great for you and your health. In fact, reading books was the only form of personal entertainment for years. If you look at the reasons for reading the book, then there can be many reasons to read it. For example, to gain knowledge, to spend time, to forget about something, to avoid any stress, to keep the brain busy, to learn writing, or for any other reason. Let us know what its benefits are."},
      {"heading": "15 Benefits Of Book Reading", "subHeading": "", "description": "The benefits of reading a book include mental benefits, health improvement, improvement in physical health, healthy habits, personal entertainment, and many other benefits, which are as follows:"},
      {"heading": "", "subHeading": "1. Prevents Alzheimer’s and Dementia", "description": "Studies have shown that reading the book daily keeps the mind mentally stimulated, reducing the likelihood of Alzheimer’s and dementia. Because your brain remains active, it prevents your mental strength from being lost. Like the body, exercise is also needed to keep the brain strong, which comes from reading books or doing puzzles and playing games like chess."},
      {"heading": "", "subHeading": "2. Reduce Stress", "description": "We all have to face many problems in our lives. Due to which many times we suffer from stress. But there are many people who read any book of their choice to reduce their stress so that their stress can be reduced. You can also read the book of your choice to reduce your stress. So that your stress can be reduced."},
      {"heading": "", "subHeading": "3. Increase Knowledge", "description": "The best advantage of reading a book is that your knowledge increases. The more knowledge you have. You will be able to do the challenge of people. Because no one knows when and where you have to face someone’s challenge. Apart from this, a knowledgeable person with his knowledge has a very deep knowledge of right and wrong."},
      {"heading": "", "subHeading": "4. Memory Booster", "description": "We all see and read many things in daily life. But you cannot remember everyone. But people who read books more, memory is better and stronger. Which helps in remembering small things."},
      {"heading": "", "subHeading": "5. Increase Concentration Power", "description": "In today’s Internet world, we are caught in different directions because we do many such tasks every day. While doing the work, we check Facebook and WhatsApp every 5 minutes, Skype to check email, chat with some people, monitor our smart-phones. Such things reduce our concentration and focus. But when you read a book, all your attention is focused on the story. That is why by reading the book our concentration and ability to focus gradually increases."},
      {"heading": "", "subHeading": "6. Build Self-confidence", "description": "When we read any book, we get to learn many such new things. This helps us to express our feelings in life and also with it our confidence."},
      {"heading": "", "subHeading": "7. Good Sleep", "description": "Do you know that reading a book can also help with your sleep? This does not mean that it helps you fall asleep, but when you read a book it exhausts your brain which helps you to get a deep and peaceful sleep. That is why if you want to sleep well then read the book before going to sleep."},
      {"heading": "", "subHeading": "8. Increase In Writing Skills", "description": "Our books expand the vocabulary in us. Which helps to increase our writing ability. As we can also influence our work by observing the rhythm, fluidity, and writing styles of other writers."},
      {"heading": "", "subHeading": "9. Mental Relax", "description": "Many people like to read their favorite books for their mental peace. Many people also believe that reading a book helps you to overcome your situation. That is why when one reads a book, one gets peace of mind."},
      {"heading": "", "subHeading": "10. Imagination Power & Analytical Skills", "description": "When you read a book, you start looking at the things written in it, the ways mentioned in it with your life, and start venturing into your life. When you read a horror/suspense novel, its characters, events start to get in your mind and you start trying to understand the conclusion of the novel without reading it completely. Reading daily increases your imagination power increases the scope of your thinking, increases the power of your thinking, understanding, and increases your analytical skills. You mature from day today."},
      {"heading": "", "subHeading": "11. Loneliness For Aways", "description": "Books are true friends of humans. They help to overcome your loneliness. Whenever you feel lonely or bored, start reading. The habit of reading fills new energy in you, removes your boredom, changes your mood, relaxes you."},
      {"heading": "", "subHeading": "12. Make You Better Person", "description": "The habit of reading daily makes many changes in your life. These increase your knowledge and make you more mature than before. Your perspective of thinking changes. Make life decisions wisely. You realize your responsibilities towards yourself, your family, relationships. You become a better person than before."},
      {"heading": "", "subHeading": "13. The Art Of Talking/Speaking/Writing is Developed", "description": "Due to a lack of information, in many places you have to remain silent, hesitation to talk, or not able to talk properly. The habit of reading daily makes you a good communicator. Reading increases your knowledge, your information, on the basis of which you can talk to anyone, anywhere, on any topic. Your speaking, talking confidence increases. You can do your thing, your own thoughts, do it better, explain it to others, write it down. He who can speak well can also write well."},
      {"heading": "", "subHeading": "14. Tranquility", "description": "Apart from the relaxation that comes with reading a good book, it is possible that the subject you read about can bring a lot of inner peace and calm. Blood pressure can be reduced by reading spiritual texts and a sense of calm while reading self-help books, which have been shown to help people suffering from certain mood disorders and mild mental illnesses. has gone."},
      {"heading": "", "subHeading": "15. Entertainment Tool", "description": "Books can be an entertainment tool for us. Many people want to entertain for less money, they can entertain themselves by reading books. If you live in an area that does not have a local library, there are many sources online for this where you can download free e-books."},
      {"heading": "", "subHeading": "Conclusion", "description": "We have explained many benefits of reading the book. By reading, you can understand how important it is for us to read the book. That is why you should read books daily and advise people to read books also."}      
    ]
  }`)

    this.router.navigate(['article']);


  }

  openSecondArticle = () =>{
    localStorage.setItem("articleObj", `{
      "title": "Positive Effects of Books in Your Life",
      "tags": ["Strengthens the brain", "Increases empathy", "Reduces stress", "Builds vocabulary"],
      "link": "../assets/carousel-6.jpg",
      "content": [
        {"heading": "", "subHeading": "Reading strengthens your brain", "description": "A growing body of research indicates that reading literally changes your mind. Using MRI scans, researchers have confirmedTrusted Source that reading involves a complex network of circuits and signals in the brain. As your reading ability matures, those networks also get stronger and more sophisticated. In one studyTrusted Source conducted in 2013, researchers used functional MRI scans to measure the effect of reading a novel on the brain. Study participants read the novel “Pompeii” over a period of 9 days. As tension built in the story, more and more areas of the brain lit up with activity. Brain scans showed that throughout the reading period and for days afterward, brain connectivity increased, especially in the somatosensory cortex, the part of the brain that responds to physical sensations like movement and pain."},
        {"heading": "", "subHeading": "Increases your ability to empathize", "description": "And speaking of sensing pain, researchTrusted Source has shown that people who read literary fiction — stories that explore the inner lives of characters — show a heightened ability to understand the feelings and beliefs of others. Researchers call this ability the “theory of mind,” a set of skills essential for building, navigating, and maintaining social relationships. While a single session of reading literary fiction isn’t likely to spark this feeling, researchTrusted Source shows that long-term fiction readers do tend to have a better-developed theory of mind."},
        {"heading": "", "subHeading": "Builds your vocabulary", "description": "Reading researchers as far back as the 1960s have discussed what’s known as “the Matthew effectTrusted Source,” a term that refers to biblical verse Matthew 13:12: “Whoever has will be given more, and they will have an abundance. Whoever does not have, even what they have will be taken from them.” The Matthew effect sums up the idea that the rich get richer and the poor get poorer — a concept that applies as much to vocabulary as it does to money. Researchers have foundTrusted Source that students who read books regularly, beginning at a young age, gradually develop large vocabularies. And vocabulary size can influence many areas of your life, from scores on standardized tests to college admissions and job opportunities. A 2019 poll conducted by Cengage showed that 69 percent of employers are looking to hire people with “soft” skills, like the ability to communicate effectively. Reading books is the best way to increase your exposure to new words, learned in context."},
        {"heading": "", "subHeading": "Reduces stress", "description": "In 2009, a group of researchers measured the effects of yoga, humor, and reading on the stress levels of students in demanding health science programs in the United States. The study found that 30 minutes of reading lowered blood pressure, heart rate, and feelings of psychological distress just as effectively as yoga and humor did. The authors concluded, “Since time constraints are one of the most frequently cited reasons for high stress levels reported by health science students, 30 minutes of one of these techniques can be easily incorporated into their schedule without diverting a large amount of time from their studies.”"},
        {"heading": "", "subHeading": "The takeaway", "description": "Reading is very, very good for you. Research shows that regular reading: improves brain connectivity increases your vocabulary and comprehension empowers you to empathize with other people aids in sleep readiness reduces stress lowers blood pressure and heart rate fights depression symptoms prevents cognitive decline as you age contributes to a longer life It’s especially important for children to read as much as possible because the effects of reading are cumulative. However, it’s never too late to begin taking advantage of the many physical and psychological benefits waiting for you in the pages of a good book."}
      ]
    }`)
  
      this.router.navigate(['article']);
  }

  openThirdArticle = () =>{
    localStorage.setItem("articleObj", `{
      "title": "Why You Should Read Every Day",
      "tags": ["Books", "Benefits", "Reading"],
      "link": "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/newscms/2018_29/2504731/180720-read-book-good-health-ac-417p.jpg",
      "content": [
        {"heading": "", "subHeading": "Mental Stimulation For Your Brain", "description": "When you read every day, you stimulate your mental activity. Numerous studies have been conducted to understand the benefits of reading. As per a study, one of the prime benefits of reading books is slowing down mental disorders such as Alzheimer’s and Dementia [1] It happens since reading stimulates the brain and keeps it active, which allows it to retain its power and capacity. Every part of our body needs exercise to stay healthy, and the same goes for our brain. Reading gives it regular exercise and keeps it healthy and sound. Even playing games like chess or solving puzzles results in cognitive stimulation"},
        {"heading": "", "subHeading": "Good Habit For Stress Reduction", "description": "Everyday concerns will keep bothering you unless you do something to divert your mind. Reading gives you that mental space to occupy yourself with something more interesting. When you read a great story, all your stress seems to slip away and relax you since you tend to travel mentally in a different realm. Sometimes while reading, you come across valuable advice or solutions to your problems."},
        {"heading": "", "subHeading": "Knowledge-Enhancement", "description": "Since the onset of civilization, we have grown and developed mentally. Many learned scholars give credit to the erudite tomes written by our predecessors for our knowledge. The importance of reading books is now more than ever since. Not everything is available in digitalized form. There are numerous ways to learn more about life, from self-help books to reading fiction. Even when you feel demotivated, you can read an inspirational biography to lift your mood. One of the great benefits of reading books is that the knowledge you gain from them can never be taken away from you. Unlike worldly possessions, your knowledge will stay with you till the end of time."},
        {"heading": "", "subHeading": "Vocabulary Expansion", "description": "If you are not yet convinced on why reading books is important, this might interest you. When you develop the habit of reading, you enhance your vocabulary. Reading any type of book can improve your vocabulary to an impressive extent. Having great command over the language is known to help many in their professional and academic life. Moreover, with better vocabulary knowledge, you get to fill yourself with self-confidence when sitting in a group with a knowledgeable audience. You can also expect to learn new languages when you develop the habit of reading various books every day."}
      ]
    }`)
  
      this.router.navigate(['article']);
  }
}
